import type { QRPreset } from '../types/qr';

export const VISUAL_PRESETS: QRPreset[] = [
  {
    id: 'cyberpunk',
    name: 'Cyberpunk Neon',
    description: 'Vibrant neon cyan to magenta gradient on deep space backdrop',
    category: 'vibrant',
    previewBadge: 'Neon',
    style: {
      foregroundColor: '#00F2FE',
      backgroundColor: '#0F172A',
      isTransparentBg: false,
      gradient: {
        type: 'linear',
        color1: '#00F2FE',
        color2: '#4FACFE',
        rotation: 45,
      },
      dotsType: 'rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      useCustomCornerColors: true,
      cornerSquareColor: '#38BDF8',
      cornerDotColor: '#F43F5E',
      margin: 2,
      errorCorrectionLevel: 'Q',
    },
  },
  {
    id: 'ocean-gradient',
    name: 'Ocean Breeze',
    description: 'Deep navy background with emerald teal to azure gradient',
    category: 'gradient',
    previewBadge: 'Gradient',
    style: {
      foregroundColor: '#0D9488',
      backgroundColor: '#F0FDF4',
      isTransparentBg: false,
      gradient: {
        type: 'linear',
        color1: '#0D9488',
        color2: '#0284C7',
        rotation: 135,
      },
      dotsType: 'classy',
      cornerSquareType: 'classy',
      cornerDotType: 'square',
      useCustomCornerColors: false,
      margin: 2,
      errorCorrectionLevel: 'M',
    },
  },
  {
    id: 'sunset-glow',
    name: 'Sunset Glow',
    description: 'Warm coral orange to fiery magenta gradient',
    category: 'vibrant',
    previewBadge: 'Sunset',
    style: {
      foregroundColor: '#F97316',
      backgroundColor: '#FAF5FF',
      isTransparentBg: false,
      gradient: {
        type: 'linear',
        color1: '#F97316',
        color2: '#EC4899',
        rotation: 90,
      },
      dotsType: 'dots',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      useCustomCornerColors: true,
      cornerSquareColor: '#E11D48',
      cornerDotColor: '#F59E0B',
      margin: 2,
      errorCorrectionLevel: 'Q',
    },
  },
  {
    id: 'emerald-luxury',
    name: 'Emerald Luxury',
    description: 'Dark royal emerald green with shimmering gold accents',
    category: 'brand',
    previewBadge: 'Luxury',
    style: {
      foregroundColor: '#D97706',
      backgroundColor: '#064E3B',
      isTransparentBg: false,
      gradient: {
        type: 'linear',
        color1: '#F59E0B',
        color2: '#FCD34D',
        rotation: 45,
      },
      dotsType: 'classy-rounded',
      cornerSquareType: 'classy',
      cornerDotType: 'dot',
      useCustomCornerColors: true,
      cornerSquareColor: '#FBBF24',
      cornerDotColor: '#F59E0B',
      margin: 2,
      errorCorrectionLevel: 'H',
    },
  },
  {
    id: 'minimal-tech',
    name: 'Minimal Tech',
    description: 'Clean high-contrast obsidian black on stark white',
    category: 'minimal',
    previewBadge: 'Classic',
    style: {
      foregroundColor: '#0F172A',
      backgroundColor: '#FFFFFF',
      isTransparentBg: false,
      gradient: {
        type: 'none',
        color1: '#0F172A',
        color2: '#334155',
        rotation: 0,
      },
      dotsType: 'square',
      cornerSquareType: 'square',
      cornerDotType: 'square',
      useCustomCornerColors: false,
      margin: 3,
      errorCorrectionLevel: 'M',
    },
  },
  {
    id: 'midnight-dark',
    name: 'Midnight Dark',
    description: 'Sleek dark theme with crisp white modules',
    category: 'dark',
    previewBadge: 'Dark',
    style: {
      foregroundColor: '#F8FAFC',
      backgroundColor: '#090D16',
      isTransparentBg: false,
      gradient: {
        type: 'none',
        color1: '#F8FAFC',
        color2: '#E2E8F0',
        rotation: 0,
      },
      dotsType: 'rounded',
      cornerSquareType: 'extra-rounded',
      cornerDotType: 'dot',
      useCustomCornerColors: false,
      margin: 2,
      errorCorrectionLevel: 'M',
    },
  },
  {
    id: 'royal-purple',
    name: 'Royal Amethyst',
    description: 'Deep violet background with electric indigo to violet gradient',
    category: 'gradient',
    previewBadge: 'Purple',
    style: {
      foregroundColor: '#6366F1',
      backgroundColor: '#1E1B4B',
      isTransparentBg: false,
      gradient: {
        type: 'linear',
        color1: '#818CF8',
        color2: '#C084FC',
        rotation: 120,
      },
      dotsType: 'dots',
      cornerSquareType: 'dot',
      cornerDotType: 'dot',
      useCustomCornerColors: true,
      cornerSquareColor: '#A855F7',
      cornerDotColor: '#818CF8',
      margin: 2,
      errorCorrectionLevel: 'Q',
    },
  },
];
